services:
  db:
    image: postgres:15
    container_name: orders_db
    env_file:
      - environment/.env
    ports:
      - "27418:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ozon_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
volumes:
  ozon_pgdata: