// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postId"`
	ParentID  *string    `json:"parentId,omitempty"`
	AuthorID  string     `json:"authorId"`
	Text      string     `json:"text"`
	CreatedAt string     `json:"createdAt"`
	Replies   []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	AuthorID        string     `json:"authorId"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	CreatedAt       string     `json:"createdAt"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
